@startuml schema_creation

title Schema Creation

:Creation of data-class;

:Add Data-class to db schema using pyodb
class annotation;

:Add column with unqiue id to table definition;

:Convert class' **primitives** to table
rows with corresponding data type;

:Convert **lists** containing only
primitive types to **stringified json**;

:Convert **dicts** containing only
primitives to **stringified json**;

while (class has members with complex types?)
    if (Class does not have a table definition?) then
        :Add sub-class to db schema;

        :Convert class' primitive types to
        table rows;
    endif

    :Define connection to parent (Link to parent's unique id);
endwhile

:Create column containing a list of
all child tables (complex types);

:Save table definition to internal table definitions;

@enduml
